[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "time-series-models"
version = "0.1.0"
dependencies = ["numpy", "pandas", "tensorflow", "torch"]